### ISSUE TITLE
Написать оформленное тз

### ISSUE THREAD

**Issue by SpaceLost** [SpaceLost/Kursach#3]

**Comment by SpaceLost** [comment]
Техническое задание
1.	Общие сведения
1.1 Полное наименование системы;
Веб-сайт компании по продаже автозапчастей.
1.2 Наименование организации-заказчика, разработчика системы:
Заказчик: Владелец компании «РусДеталь».
Разработчик: Студент КФ МГТУ им. Н.Э. Баумана группы ИУК5-51Б Корнеев К.М.
1.3 Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ - 4 сентября 2024 года
Плановый срок окончания работ - 1 декабря 2024 года
2.	Назначение и цели создания системы
2.1 Назначение системы:
Система предназначена для клиентов и администраторов компании.
Клиенты: заказ запчастей.
Администраторы: сокращение нагрузки.
2.2 Цели создания системы:
Система создается для увеличения количества клиентов и доходов.
3.	Характеристика объектов автоматизации
3.1 Объект автоматизации:
4.	Объектом автоматизации является процесс заказа запчастей клиентом.
Клиент звонит в компанию для того, чтобы узнать наличие нужной запчасти, сроке и способе поставки. При заказе клиент вносит полную предоплату, в случае получения клиентом неисправной запчасти(брак), компания возвращает предоплату. Администратор компании вносит информацию о клиенте, запчасти, дате и способе доставки в excel файл.
5.	Требования к системе
4.1 Требования к системе в целом: Система должна предоставлять функционал взаимодействия с сайтом для клиентов и администраторов.
4.2 Требования к функционалу системы:
4.2.1 Функционал пользователя в целом:
•	Регистрация
•	Авторизация
•	Подтверждение номера телефона
•	Подтверждение электронной почты
4.2.2 Функционал администратора:
•	Функционал, описанный в пункте 4.2.1
•	Управление заказами (подтверждение, отмена)
•	Модерация, сопровождение сайта
•	Добавление/удаление/редактирование карточек запчастей
4.2.3 Функционал клиента (авторизованный пользователь):
•	Функционал, описанный в пункте 4.2.1(кроме регистрации)
•	Поиск запчастей
•	Просмотр характеристик запчастей (совместимость, артикул, производитель, цена, срок доставки)
•	Добавление запчастей в корзину
•	Возможность оформить заказ
•	Оставление отзыва
•	Подтверждение заказа через звонок администратором
•	Выход из аккаунта
•	Смена пароля
4.2.4 Функционал неавторизованного пользователя:
•	Функционал, описанный в пункте 4.2.1
•	Поиск запчастей
•	Просмотр характеристик запчастей (совместимость, артикул, производитель, цена, срок доставки)
5.	Состав и содержание работ по созданию автоматизированной системы
Дедлайн 12-15 сентября:
o	Утверждение темы, задания на разработку, технического задания (альфа)
Дедлайн 26-29 сентября:
o	Оформление ТЗ
o	Описание предметной области и требований к системе.
o	Рассмотрение аналогов
o	Проектировка концептуальной схемы
o	Составление прототипа или скетчей интерфейса (API, если интерфейса нет)
Дедлайн 7 ноября:
o	Оформление проектно-конструкторской части
o	Демонстрация работающего приложения
o	Создание презентации (альфа)
o	Тестирование и отладка приложения
o	Разработка эксплуатационной документации
Дедлайн 1 декабря:
o	Устранение всех ошибок и проблем
6.	Порядок контроля и приемки системы
Контроль и приемка результатов работ будут осуществляться на каждой стадии создания системы в соответствии с разделом 5.
7.	Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ.
8.	Требования к документированию
Должны быть предоставлены:
•	Техническое задание в соответствии с ГОСТ 34.602-2020
•	Расчетно-пояснительная записка в соответствии с ГОСТ 2.106-96
9.	Источники разработки
•

**Comment by wldmr-key** [comment]
объект автоматизации стоило бы определить - допустим, процесс заказа запчастей клиентом....

нуждается в пояснении:
>сопровождение сайта
• Внесение/удаление/редактирование полей

каких еще полей?!

откуда запчасти вообще появляются в системе?

**Comment by SpaceLost** [comment]
Под полями я имел ввиду ""карточки запчастей"".
В случае если появляется новая запчасть/аналог в доступ (а компания-ритейлер для которой создается сайт хочет иметь возможность поддержки актуальности своего ассортимента), администратор имеет возможность добавить новую запчасть в ассортимент сайта

**Comment by wldmr-key** [comment]
так перепиши все в виде, не требующем пояснений (и, да, тебе нужен ревьювер, чтобы прочитал, что получилось и проверил ошибки)

**Comment by SpaceLost** [comment]
Исправил

**Comment by wldmr-key** [comment]
плохо исправил
чем отличается "пользователь в целом" от "авторизованного пользователя"? А чем отличаются из функции. Прочитай внимательно. Потом прочитай внимательно еще раз.

**Comment by SpaceLost** [comment]
Поправил

**Comment by wldmr-key** [comment]
Функционал неавторизованного пользователя:
• Функционал, описанный в пункте 4.2.1

4.2.1 Функционал пользователя в целом:
...
• Выход из аккаунта
• Смена пароля

только я вижу, что это полная фигня?

**Comment by SpaceLost** [comment]
Все понял, все осознал, все исправил)

**Comment by wldmr-key** [comment]
напиши целиком ТЗ в следующем комментарии, чтобы я по исправлениям не шарился

**Comment by SpaceLost** [comment]
Техническое задание
1.	Общие сведения
1.1 Полное наименование системы;
Веб-сайт компании по продаже автозапчастей.
1.2 Наименование организации-заказчика, разработчика системы:
Заказчик: Владелец компании «РусДеталь».
Разработчик: Студент КФ МГТУ им. Н.Э. Баумана группы ИУК5-51Б Корнеев К.М.
1.3 Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ - 4 сентября 2024 года
Плановый срок окончания работ - 1 декабря 2024 года
2.	Назначение и цели создания системы
2.1 Назначение системы:
Система предназначена для клиентов и администраторов компании.
Клиенты: заказ запчастей.
Администраторы: сокращение нагрузки.
2.2 Цели создания системы:
Система создается для увеличения количества клиентов и доходов.
3.	Характеристика объектов автоматизации
3.1 Объект автоматизации:
4.	Объектом автоматизации является процесс заказа запчастей клиентом.
Клиент звонит в компанию для того, чтобы узнать наличие нужной запчасти, сроке и способе поставки. При заказе клиент вносит полную предоплату, в случае получения клиентом неисправной запчасти(брак), компания возвращает предоплату. Администратор компании вносит информацию о клиенте, запчасти, дате и способе доставки в excel файл.
5.	Требования к системе
4.1 Требования к системе в целом: Система должна предоставлять функционал взаимодействия с сайтом для клиентов и администраторов.
4.2 Требования к функционалу системы:
4.2.1 Функционал пользователя в целом:
•	Регистрация
•	Авторизация
•	Подтверждение номера телефона
•	Подтверждение электронной почты
4.2.2 Функционал администратора:
•	Функционал, описанный в пункте 4.2.1
•	Управление заказами (подтверждение, отмена)
•	Модерация, сопровождение сайта
•	Добавление/удаление/редактирование карточек запчастей
4.2.3 Функционал клиента (авторизованный пользователь):
•	Функционал, описанный в пункте 4.2.1(кроме регистрации)
•	Поиск запчастей
•	Просмотр характеристик запчастей (совместимость, артикул, производитель, цена, срок доставки)
•	Добавление запчастей в корзину
•	Возможность оформить заказ
•	Оставление отзыва
•	Подтверждение заказа через звонок администратором
•	Выход из аккаунта
•	Смена пароля
4.2.4 Функционал неавторизованного пользователя:
•	Функционал, описанный в пункте 4.2.1
•	Поиск запчастей
•	Просмотр характеристик запчастей (совместимость, артикул, производитель, цена, срок доставки)
5.	Состав и содержание работ по созданию автоматизированной системы
Дедлайн 12-15 сентября:
o	Утверждение темы, задания на разработку, технического задания (альфа)
Дедлайн 26-29 сентября:
o	Оформление ТЗ
o	Описание предметной области и требований к системе.
o	Рассмотрение аналогов
o	Проектировка концептуальной схемы
o	Составление прототипа или скетчей интерфейса (API, если интерфейса нет)
Дедлайн 7 ноября:
o	Оформление проектно-конструкторской части
o	Демонстрация работающего приложения
o	Создание презентации (альфа)
o	Тестирование и отладка приложения
o	Разработка эксплуатационной документации
Дедлайн 1 декабря:
o	Устранение всех ошибок и проблем
6.	Порядок контроля и приемки системы
Контроль и приемка результатов работ будут осуществляться на каждой стадии создания системы в соответствии с разделом 5.
7.	Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в ТЗ.
8.	Требования к документированию
Должны быть предоставлены:
•	Техническое задание в соответствии с ГОСТ 34.602-2020
•	Расчетно-пояснительная записка в соответствии с ГОСТ 2.106-96
9.	Источники разработки
•

**Comment by wldmr-key** [comment]
сойдет, хотя выделение "пользователя в целом" это, конечно, сюр
