### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by SpaceLost** [SpaceLost/Kursach#4]

**Comment by SpaceLost** [comment]
Описание предметной области и требований к системе
Разрабатываемая система должна автоматизировать ключевые процессы компании по продаже автомобильных запчастей, снизить необходимость в ручном труде, сделать взаимодействие с клиентами и сотрудниками более комфортным, а также улучшить контроль над ресурсами и повысить доходность компании.
Сфера деятельности компании по продаже автозапчастей включает предоставление таких услуг как: поиск нужной запчасти и соответственно продажу запчастей.
Предметная область охватывает все процессы, связанные с предоставлением услуг компании по продаже автозапчастей, в частности, процесс заказа клиентами автозапчастей, взаимодействия между администратором компании и клиентами.
В настоящее время процесс заказа запчастей выполняется вручную — администратор компании регистрирует звонки клиентов и вносит информацию в таблицы Excel. Этот процесс сопровождается определенными сложностями при внесении данных и ограниченный доступ клиентов к актуальной информации.
Прейскурант:
В компании существует фиксированный прейскурант на запчасти, включающий стандартные цены на каждую из них. Стоимость заказа запчасти может варьироваться в зависимости от выбранного способа доставки. Клиенты вносят полную предоплату за заказ, а также могут отказаться от заказа и вернуть предоплату в случае, если запчасть получена с браком/ неисправна/ «не то что заказали», что делает процесс заказа более удобным.
В разрабатываемой системе функция должна быть такой:
Система должна автоматизировать процесс заказа запчастей клиентами. В разрабатываемой системе клиент сможет самостоятельно сделать заказ через веб-интерфейс, выбрать способ и время доставки, а также ознакомиться с прейскурантом и описанием каждой запчасти.
Авторизованный клиент заходит на сайт (он может выйти из личного кабинета, сменить пароль), просматривает ассортимент, ищет нужные запчасти и цены на них. Может прочитать о запчасти подробнее, удостовериться в её совместимости, ознакомиться с прайсом, сроками и способами доставки, а также производителями запчастей. Далее клиент выбирает запчасть, способ доставки и добавляет данную запчасть в корзину (при желании может выбрать несколько запчастей), тем самым формируется заказ. После этого ему на почту приходит сообщение с подтверждением его заказа, где прописаны его дата, запчасть(-и), способ доставки(если доставка в пункт выдачи, то прописывается адрес пвз). После получения запчасти у них появляется возможность оставить отзыв на сайте.
Неавторизованный клиент прежде, чем проделать все то же самое, проходит регистрацию на сайте, а именно вписывает свои данные (ФИО, email и номер телефона), затем проходит подтверждение номера телефона, клиенту высылается смс код на номер телефона, после этого он придумывает пароль (логином будет являться почта или номер телефона) и повторяет его.
Администратор компании – также авторизованный пользователь, но с рабочей почтой и после входа в ЛК попадает в раздел с заказами от клиентов - следит за обновлениями ассортимента и вносит их на сайт. Также он получает все заказы от клиентов, подтверждает их и вносит данные в реестр заказов. Он имеет доступ к информации о клиентах.
Также, когда запчасть прибыла в пвз, клиент получает оповещение на почту, что заказ можно забрать, если заказ оформлен доставкой курьера, то в день доставки курьер звонит клиенту для согласования удобного времени получения заказа. В случае задержки заказа, клиент также получит оповещение на почту.
Основные объекты предметной области:
Компания
Администратор
Клиент
Заказ
Запчасть
Реестр
Система должна автоматизировать процесс заказа автозапчастей клиентами.
Основные функции системы:
Регистрация и авторизация пользователей (клиентов, администраторов);
Управление клиентами:
• Хранение и управление данными о клиентах (имя, контактные данные, история заказов). 
Управление запчастями:
• Хранение и управление данными о запчастях (название, описание, стоимость).
Процесс заказа клиентами:
• Предоставление клиентам возможности сделать заказ через веб-интерфейс, выбрать способ доставки. 
• Отправка подтверждений и напоминаний клиентам по электронной почте.
Интеграция с внешними системами:
• Интеграция с системами электронной почты и SMS.

**Comment by wldmr-key** [comment]
а, откуда берутся, собственно, запчасти? не администратор же их делает. Вполне допустимо, чтобы процесс происходил вне системы, но данные-то для него нужно готовить!

**Comment by SpaceLost** [comment]
Описание предметной области и требований к системе

Разрабатываемая система должна автоматизировать ключевые процессы компании по продаже автомобильных запчастей, снизить необходимость в ручном труде, сделать взаимодействие с клиентами и сотрудниками более комфортным, а также улучшить контроль над ресурсами и повысить доходность компании.
Сфера деятельности компании по продаже автозапчастей включает предоставление таких услуг как: поиск нужной запчасти и соответственно продажу запчастей.

Предметная область охватывает все процессы, связанные с предоставлением услуг компании по продаже автозапчастей, в частности, процесс заказа клиентами автозапчастей, взаимодействия между администратором компании и клиентами.

В настоящее время процесс заказа запчастей выполняется вручную — администратор компании регистрирует звонки клиентов и вносит информацию в таблицы Excel. Этот процесс сопровождается определенными сложностями при внесении данных и ограниченный доступ клиентов к актуальной информации.

Прейскурант:
В компании существует фиксированный прейскурант на запчасти, включающий стандартные цены на каждую из них. Стоимость заказа запчасти может варьироваться в зависимости от выбранного способа доставки. Клиенты вносят полную предоплату за заказ, а также могут отказаться от заказа и вернуть предоплату в случае, если запчасть получена с браком/ неисправна/ «не то что заказали», что делает процесс заказа более удобным.

Запчасти: 
Клиент создает заказ, администратор делает звонок для уточнения информации по наличию детали и способе доставки. Далее администратор отправляет заказ на склад, там работник склада получает заказ и по штрих-коду товара, привязанного к артикулу, находит нужные комплектующие, сканирует каждую из них (чтобы в системе эта комплектующая учитывалась в заказ и в дальнейшем корректно отображалось наличие конкретного товара), после чего работник склада упаковывает заказ в одно целое, присваивает трэк-номер заказа и отправляет на этап доставки. На этапе доставки заказ так же сканируется(чтобы отслеживать заказ на каждом этапе: от сборки до доставки), грузится в транспорт, сотрудничающей транспортной компании и доставляется до сортировочного центра, находящегося в городе доставки, после чего в пункт выдачи(ПВЗ) и клиенту приходит уведомление о доставленном заказе, если способ доставки был выбран курьером, то после предыдущего действия курьер забирает заказ из пвз, созванивается с клиентом для уточнения времени доставки. Клиент забирает заказ, в случае брака/не соответствия и т.п. клиент вправе сразу оформить возврат. Возврат происходит с точностью наоборот доставке: курьер возвращает заказ на пункт выдачи, сотрудник пункта выдачи сканирует штрих-код заказа, вводит в системе статус заказа-возврат, далее заказ передается на доставку на склад, на складе заказ принимается (сканируется и проверяются комплектующие), в случае если комплектующие в порядке, работник склада возвращает их на свои места, предварительно просканировав для добавления в систему, в случае неисправности/брака, запчасть отправляется на утилизацию. После каждого заказа обновляется наличие запчасти, если запчасть заканчивается на складе, для поддержания наличия, администратор создает заявки на закупку запчастей в необходимом количестве и отправляет данную заявку в электронном виде поставщику-производителю. 

В разрабатываемой системе функция должна быть такой:
Система должна автоматизировать процесс заказа запчастей клиентами. В разрабатываемой системе клиент сможет самостоятельно сделать заказ через веб-интерфейс, выбрать способ и время доставки, а также ознакомиться с прейскурантом и описанием каждой запчасти.

Авторизованный клиент заходит на сайт (он может выйти из личного кабинета, сменить пароль), просматривает ассортимент, ищет нужные запчасти и цены на них. Может прочитать о запчасти подробнее, удостовериться в её совместимости, ознакомиться с прайсом, сроками и способами доставки, а также производителями запчастей. Далее клиент выбирает запчасть, способ доставки и добавляет данную запчасть в корзину (при желании может выбрать несколько запчастей), тем самым формируется заказ. После этого ему на почту приходит сообщение с подтверждением его заказа, где прописаны его дата, запчасть(-и), способ доставки(если доставка в пункт выдачи, то прописывается адрес пвз). После получения запчасти у них появляется возможность оставить отзыв на сайте.

Неавторизованный клиент прежде, чем проделать все то же самое, проходит регистрацию на сайте, а именно вписывает свои данные (ФИО, email и номер телефона), затем проходит подтверждение номера телефона, клиенту высылается смс код на номер телефона, после этого он придумывает пароль (логином будет являться почта или номер телефона) и повторяет его.

Администратор компании – также авторизованный пользователь, но с рабочей почтой и после входа в ЛК попадает в раздел с заказами от клиентов - следит за обновлениями ассортимента и вносит их на сайт. Также он получает все заказы от клиентов, подтверждает их и вносит данные в реестр заказов. Он имеет доступ к информации о клиентах.
Также, когда запчасть прибыла в пвз, клиент получает оповещение на почту, что заказ можно забрать, если заказ оформлен доставкой курьера, то в день доставки курьер звонит клиенту для согласования удобного времени получения заказа. В случае задержки заказа, клиент также получит оповещение на почту.

Основные объекты предметной области:
Компания
Администратор
Клиент
Заказ
Запчасть
Реестр

Система должна автоматизировать процесс заказа автозапчастей клиентами.

Основные функции системы:
Регистрация и авторизация пользователей (клиентов, администраторов);
Управление клиентами:
• Хранение и управление данными о клиентах (имя, контактные данные, история заказов). 
Управление запчастями:
• Хранение и управление данными о запчастях (название, описание, стоимость).
Процесс заказа клиентами:
• Предоставление клиентам возможности сделать заказ через веб-интерфейс, выбрать способ доставки. 
• Отправка подтверждений и напоминаний клиентам по электронной почте.
Интеграция с внешними системами:
• Интеграция с системами электронной почты и SMS.

**Comment by wldmr-key** [comment]
приемлемо
